spring:
  application:
    name: eureka_server
port_num:
  peer1: 8761
  peer2: 8762

---
spring:
  profiles: peer2
eureka:
  instance:
    hostname: peer2
  client:
    serviceUrl:
      defaultZone: http://peer1:${port_num.peer1}/eureka/
    register-with-eureka: true
    fetch-registry: true
server:
  port: ${port_num.peer2}
---
spring:
  profiles: peer1
eureka:
  instance:
    hostname: peer1
  client:
    serviceUrl:
      defaultZone: http://peer2:${port_num.peer2}/eureka/
    register-with-eureka: true
    fetch-registry: true
server:
  port: ${port_num.peer1}
      